theme: jekyll-theme-minimal
title: Jeremys page
description: My name is Jeremy Karam. I am a final year PhD. student studying the formation of young massive star clusters through dynamics. Welcome to my website.
